export const NUMBERS = [
  { spanish: "uno", english: "1" },
  { spanish: "dos", english: "2" },
  { spanish: "tres", english: "3" },
  { spanish: "cuatro", english: "4" },
  { spanish: "cinco", english: "5" },
  { spanish: "seis", english: "6" },
  { spanish: "siete", english: "7" },
  { spanish: "ocho", english: "8" },
  { spanish: "nueve", english: "9" },
  { spanish: "diez", english: "10" },
  { spanish: "once", english: "11" },
  { spanish: "doce", english: "12" },
  { spanish: "trece", english: "13" },
  { spanish: "catorce", english: "14" },
  { spanish: "quince", english: "15" },
  { spanish: "dieciséis", english: "16" },
  { spanish: "diecisiete", english: "17" },
  { spanish: "dieciocho", english: "18" },
  { spanish: "diecinueve", english: "19" },
  { spanish: "veinte", english: "20" },
  { spanish: "veintiuno", english: "21" },
  { spanish: "veintidós", english: "22" },
  { spanish: "veintitrés", english: "23" },
  { spanish: "veinticuatro", english: "24" },
  { spanish: "veinticinco", english: "25" },
  { spanish: "veintiséis", english: "26" },
  { spanish: "veintisiete", english: "27" },
  { spanish: "veintiocho", english: "28" },
  { spanish: "veintinueve", english: "29" },
  { spanish: "treinta", english: "30" },
  { spanish: "treinta y uno", english: "31" },
  { spanish: "treinta y dos", english: "32" },
  { spanish: "treinta y tres", english: "33" },
  { spanish: "cuarenta", english: "40" },
  { spanish: "cuarenta y uno", english: "41" },
  { spanish: "cuarenta y dos", english: "42" },
  { spanish: "cincuenta", english: "50" },
  { spanish: "sesenta", english: "60" },
  { spanish: "setenta", english: "70" },
  { spanish: "ochenta", english: "80" },
  { spanish: "noventa", english: "90" },
  { spanish: "cien", english: "100" },
  { spanish: "ciento uno", english: "101" },
  { spanish: "ciento dos", english: "102" },
  { spanish: "ciento diez", english: "110" },
  { spanish: "ciento once", english: "111" },
  { spanish: "doscientos", english: "200" },
  { spanish: "doscientos uno", english: "201" },
  { spanish: "doscientos dos", english: "202" },
  { spanish: "doscientos once", english: "211" },
  { spanish: "doscientos setenta y seis", english: "276" },
  { spanish: "trescientos", english: "300" },
  { spanish: "cuatrocientos", english: "400" },
  { spanish: "quinientos", english: "500" },
  { spanish: "seiscientos", english: "600" },
  { spanish: "setecientos", english: "700" },
  { spanish: "ochocientos", english: "800" },
  { spanish: "novecientos", english: "900" },
  { spanish: "mil", english: "1.000" },
  { spanish: "mil once", english: "1.011" },
  { spanish: "mil ciento once", english: "1.111" },
  { spanish: "dos mil", english: "2.000" },
];
